[buildPlans.square]
family = 'Iosevka Square'

[buildPlans.square.variants.design]
punctuation = 'square'

[buildPlans.square.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.square.slopes]
upright = 'normal'

[buildPlans.square.widths.normal]
shape = 500
menu  = 5
css   = 'normal'
